### PR TITLE
Allow compiler customization

### PR DESCRIPTION
**Pull request by dreua**

### CODE REVIEW

**Comment by cnlohr** [comment]
I'm merging, but this *should* be ?=

**Comment by dreua** [comment]
It depends what you want, but both is totally fine with me. The difference is subtle:
`CC=gcc`: You can overwrite CC via `make CC="whatever"`
`CC?=gcc`: You can overwrite CC via `make CC="whatever"` *or* environment variable, e.g. `CC="whatever" make`, in your .bashrc file or something like that.

**Comment by cnlohr** [comment]
Interesting, I was unaware you could override so easily with a regular = instead of a ?= .  What is your preference?

**Comment by dreua** [comment]
I thought CC=gcc was less intrusive at first, but now I'd say lets keep it at ?=. The void package works that way and I believe that anyone having problems with $CC set in their environment knows how to deal with it.

**Pull request merged**
