### PR TITLE
Feature/argp

### PR DESCRIPTION
**Pull request by drbachler**

### CODE REVIEW

**Comment by cnlohr** [comment]
gaaaaahhhhhh I should have checked before I did my committtttttttttt

**Comment by cnlohr** [comment]
give me a while to dig through this and I'll merge.

**Comment by cnlohr** [comment]
I'm really sorry, I worked on this yesterday and just forgot to commit.  I think we should discuss this.  I want to maintain close compatibility to ping if we're gonna do it, i.e. -s is added ping size, etc.  Also, It "feels" like more code to go the argp route.  What benefit does it include?

**Comment by drbachler** [comment]
Hi Charles,
I just had a go at some other kind of argument parsing.
argp seemed like it was a good choice.

> Argp provides features unavailable in the more commonly used getopt interface. These features include automatically producing output in response to the ‘--help’ and ‘--version’ options, as described in the GNU coding standards. Using argp makes it less likely that programmers will neglect to implement these additional options or keep them up to date.

(https://www.gnu.org/software/libc/manual/html_node/Argp.html)
I also wanted to learn about argp.

It would be easy to just adjust the option keys to match the ones of ping I guess? (Would that be whats needed?) I didn't really think about keeping it like ping, but that sound like the way to go.

Regarding your feeling of there being a lot of code, can you elaborate a bit? What alternatives did you have in mind?

**Comment by drbachler** [comment]
I think we should go with Charlses solution in this case.

**Comment by cnlohr** [comment]
@drbachler Thank you for the effort.  

P.S. I saw you were prepping it for arch linux?  How did that go?  I don't know anything about getting into mainline Linux distributions, but it would be really cool if this could be something I could use without downloading on things like Debian or Mint.

**Pull request closed without merging**
