### PR TITLE
OSX: window resize added

### PR DESCRIPTION
**Pull request by Viknet**

### CODE REVIEW

**Comment by cnlohr** [comment]
I appreciate these cnping commits, however, cnlohr/rawdraw is what really needs everything since that's the upstream for rawdraw.

**Comment by cnlohr** [comment]
Also, rawdraw has test examples to make sure everything running smoothly.

**Comment by Viknet** [comment]
I will copy this change to rawdraw :)

**Comment by Viknet** [comment]
Quick question: rawdraw demo has blue background with red grid or red background with blue grid?

**Comment by cnlohr** [comment]
blue background, red grid.  I think?   If rawdraw is inconsistent with cnping I would be very confused.

**Comment by Viknet** [comment]
I just saw that old rawdraw cocoa driver (with rasterizer) colors it backwards.
It was never here.

**Pull request merged**
