### PR TITLE
Build exe with OpenGL

### PR DESCRIPTION
**Pull request by dreua**
Fixes black and white after minimize on Windows https://github.com/cnlohr/cnping/issues/54
The exe is built on Ubuntu running as Linux subsystem on Windows 10.

### CODE REVIEW

**Comment by dreua** [comment]
For me OpenGL works fine but I have no knowledge of the stability or availability of OpenGL. If objections in this area exists, this PR should probably not be merged.

**Comment by cnlohr** [comment]
This is a little scary atm.  I'm going to be going through pull requests, etc.  We should investigate backporting these into rawdraw, itself.

**Comment by dreua** [comment]
If you find building with opengl scary then we shouldn't do it. If the amount of change is what scares you, I'm sorry that became a bit of a mess, here is the explanation:
If I remember correctly I made the pull request to rawdraw first and then copied the whole file from rawdraw over to cnping and then making this pull request out of it, therefore no backporting is needed (just merging my pr). There are some changes in rawdra that weren't in cnping already and I thought it wouldn't hurt to pull them in, making cnping's rawdraw more even with rawdraw.

**Comment by cnlohr** [comment]
@dreua  OSNAP I JUST SAW YOUR SUGGESTIONS TO RAWDRAW.  I will go through them.

I am opposed to using OpenGL as the default renderer for cnping, but that is more out of a system compatibility point of view.  I would like cnping to be virtually universal.  I wish I knew what we were doing wrong in `CreateWindow` :(

**Comment by cnlohr** [comment]
I am closing this pull request, but I am considering entertaining this option in the future.

**Pull request closed without merging**
